# RE-Architect Test Configuration File - Mock Mode

# Decompiler settings
decompiler:
  # Use mock decompiler for testing when real ones aren't available
  default: mock
  
  # Mock decompiler for testing
  mock:
    enabled: true
  
  # Ghidra settings (disabled for testing)
  ghidra:
    path: null
    headless: true
    timeout: 600
    analyze_all: true
    analyze_data: true
  
  # IDA Pro settings (disabled for testing)
  ida:
    path: null
    headless: true
    timeout: 600
    idc_path: null
  
  # Binary Ninja settings (disabled for testing)
  binary_ninja:
    path: null
    timeout: 600
    analysis_mode: full

# Analysis settings
analysis:
  # Static analysis settings
  static:
    function_analysis_depth: basic  # Reduced for testing
    data_flow_analysis: true
    control_flow_analysis: true
    symbolic_execution: false
    taint_analysis: false
    string_analysis: true
    call_graph_analysis: true
  
  # Dynamic analysis settings (disabled for testing)
  dynamic:
    enable: false
    max_execution_time: 60
    memory_limit: 2048
    sandbox_type: container
    record_syscalls: true
    record_network: true
    emulation_mode: qemu

# LLM settings (mock mode for testing)
llm:
  enable: true
  provider: mock  # Use mock provider for testing
  model: mock-gpt-4
  api_key: null
  max_tokens: 8192
  temperature: 0.2
  cache_dir: ./cache/llm
  streaming: false  # Disabled for testing
  function_templates:
    - name: standard
      prompt: "Analyze this function and provide a summary of its purpose, inputs, outputs, and potential vulnerabilities."
    - name: security
      prompt: "Analyze this function for security vulnerabilities such as buffer overflows, use-after-free, and other common issues."

# Data structure recovery settings
data_structures:
  recovery_method: static  # Simplified for testing
  field_analysis: true
  pointer_analysis: true
  array_detection: true
  type_inference: true

# Test generation settings (simplified)
test_generation:
  sanitizers: [address]
  fuzzing_time: 30  # Reduced for testing
  fuzzing_engine: libfuzzer
  max_test_cases: 3  # Reduced for testing
  compiler: gcc
  compiler_flags: [-O0, -g]
  coverage_threshold: 50

# Visualization settings
visualization:
  server:
    host: localhost
    port: 5000
    debug: true  # Enable debug for testing
    auth_required: false
  ui:
    theme: dark
    show_disassembly: true
    show_decompiled: true
    show_graph: true
    show_data_flow: true

# Output settings
output:
  detail_level: basic  # Reduced for testing
  formats: [json]  # JSON only for testing
  output_dir: ./results
  reports:
    generate_pdf: false
    include_graphs: true
    include_data_structures: true
    include_test_cases: true

# Performance settings
performance:
  parallelism: 2  # Reduced for testing
  memory_limit: 4096
  disk_cache: true
  cache_dir: ./cache

# Logging settings
logging:
  level: info
  file: re-architect-test.log
  console: true
  format: "{time} [{level}] {message}"