openapi: 3.1.0
info:
  title: RE-Architect API
  description: API for RE-Architect binary analysis platform
  version: 0.1.0
  contact:
    name: RE-Architect Team
    url: https://github.com/yourusername/re-architect
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:5000/api
    description: Local development server
  - url: https://api.re-architect.yourdomain.com/api
    description: Production API server

tags:
  - name: metadata
    description: Binary metadata operations
  - name: functions
    description: Function analysis operations
  - name: data-structures
    description: Data structure operations
  - name: tests
    description: Test harness operations
  - name: summary
    description: Summary information operations
  - name: performance
    description: Performance metrics operations

paths:
  /metadata:
    get:
      summary: Get binary metadata
      description: Returns metadata about the analyzed binary file
      tags:
        - metadata
      responses:
        '200':
          description: Metadata successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Metadata'
        '404':
          description: No binary analysis data found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /functions:
    get:
      summary: Get all functions
      description: Returns all functions identified in the binary
      tags:
        - functions
      responses:
        '200':
          description: Functions successfully retrieved
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/Function'
        '404':
          description: No functions found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /function/{functionId}:
    get:
      summary: Get function details
      description: Returns details about a specific function
      tags:
        - functions
      parameters:
        - name: functionId
          in: path
          required: true
          schema:
            type: string
          description: Function ID
      responses:
        '200':
          description: Function details successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Function'
        '404':
          description: Function not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /data_structures:
    get:
      summary: Get all data structures
      description: Returns all data structures identified in the binary
      tags:
        - data-structures
      responses:
        '200':
          description: Data structures successfully retrieved
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/DataStructure'
        '404':
          description: No data structures found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /data_structure/{structId}:
    get:
      summary: Get data structure details
      description: Returns details about a specific data structure
      tags:
        - data-structures
      parameters:
        - name: structId
          in: path
          required: true
          schema:
            type: string
          description: Data structure ID
      responses:
        '200':
          description: Data structure details successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DataStructure'
        '404':
          description: Data structure not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /test_harnesses:
    get:
      summary: Get all test harnesses
      description: Returns all generated test harnesses
      tags:
        - tests
      responses:
        '200':
          description: Test harnesses successfully retrieved
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  $ref: '#/components/schemas/TestHarness'
        '404':
          description: No test harnesses found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /test_harness/{functionId}:
    get:
      summary: Get test harness for a function
      description: Returns the test harness for a specific function
      tags:
        - tests
      parameters:
        - name: functionId
          in: path
          required: true
          schema:
            type: string
          description: Function ID
      responses:
        '200':
          description: Test harness successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TestHarness'
        '404':
          description: Test harness not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /analysis/{analysisId}:
    get:
      summary: Get analysis results
      description: Returns results of a specific analysis type
      tags:
        - metadata
      parameters:
        - name: analysisId
          in: path
          required: true
          schema:
            type: string
          description: Analysis ID (static, dynamic, symbolic)
      responses:
        '200':
          description: Analysis results successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalysisResult'
        '404':
          description: Analysis not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /performance:
    get:
      summary: Get performance metrics
      description: Returns performance metrics of the analysis
      tags:
        - performance
      responses:
        '200':
          description: Performance metrics successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceMetrics'
        '404':
          description: No performance metrics found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /summary:
    get:
      summary: Get summary information
      description: Returns summary statistics of the analysis
      tags:
        - summary
      responses:
        '200':
          description: Summary successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Summary'
        '404':
          description: No summary information found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Metadata:
      type: object
      properties:
        file_path:
          type: string
          description: Path to the analyzed binary file
        file_format:
          type: string
          description: Format of the binary file (ELF, PE, Mach-O)
        architecture:
          type: string
          description: Architecture of the binary (x86, ARM, etc.)
        entry_point:
          type: string
          description: Entry point address
        size:
          type: integer
          description: Size of the binary in bytes
        sections:
          type: array
          items:
            $ref: '#/components/schemas/Section'
          description: Sections in the binary
        symbols:
          type: integer
          description: Number of symbols in the binary
        imports:
          type: array
          items:
            $ref: '#/components/schemas/Import'
          description: Imported libraries
        timestamp:
          type: string
          format: date-time
          description: Timestamp of the analysis

    Section:
      type: object
      properties:
        name:
          type: string
          description: Name of the section
        address:
          type: string
          description: Address of the section
        size:
          type: integer
          description: Size of the section in bytes

    Import:
      type: object
      properties:
        name:
          type: string
          description: Name of the imported library
        functions:
          type: integer
          description: Number of functions imported from the library

    Function:
      type: object
      properties:
        id:
          type: string
          description: Function ID
        name:
          type: string
          description: Function name
        address:
          type: string
          description: Address of the function
        size:
          type: integer
          description: Size of the function in bytes
        complexity:
          type: string
          description: Complexity assessment (Low, Medium, High)
        decompiled_code:
          type: string
          description: Decompiled code
        summary:
          type: string
          description: Summary of function behavior
        parameters:
          type: array
          items:
            $ref: '#/components/schemas/Parameter'
          description: Function parameters
        returns:
          $ref: '#/components/schemas/ReturnType'
          description: Return value information
        calls:
          type: array
          items:
            type: string
          description: Functions called by this function
        called_by:
          type: array
          items:
            type: string
          description: Functions that call this function
        confidence:
          type: number
          format: float
          description: Confidence score for analysis (0.0-1.0)
        vulnerabilities:
          type: array
          items:
            $ref: '#/components/schemas/Vulnerability'
          description: Potential vulnerabilities detected

    Parameter:
      type: object
      properties:
        name:
          type: string
          description: Parameter name
        type:
          type: string
          description: Parameter type
        description:
          type: string
          description: Parameter description

    ReturnType:
      type: object
      properties:
        type:
          type: string
          description: Return type
        description:
          type: string
          description: Return value description

    Vulnerability:
      type: object
      properties:
        type:
          type: string
          description: Type of vulnerability
        severity:
          type: string
          description: Severity level (Low, Medium, High, Critical)
        description:
          type: string
          description: Description of the vulnerability
        location:
          type: object
          properties:
            line:
              type: integer
              description: Line number in decompiled code
            column:
              type: integer
              description: Column number in decompiled code

    DataStructure:
      type: object
      properties:
        id:
          type: string
          description: Data structure ID
        name:
          type: string
          description: Data structure name
        size:
          type: integer
          description: Size in bytes
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
          description: Fields in the data structure
        description:
          type: string
          description: Description of the data structure
        references:
          type: array
          items:
            type: string
          description: Functions that reference this data structure
        confidence:
          type: number
          format: float
          description: Confidence score for analysis (0.0-1.0)

    Field:
      type: object
      properties:
        name:
          type: string
          description: Field name
        type:
          type: string
          description: Field type
        offset:
          type: integer
          description: Offset in bytes
        size:
          type: integer
          description: Size in bytes
        description:
          type: string
          description: Field description

    TestHarness:
      type: object
      properties:
        function_id:
          type: string
          description: ID of the function being tested
        function_name:
          type: string
          description: Name of the function being tested
        test_code:
          type: string
          description: Generated test harness code
        test_cases:
          type: array
          items:
            $ref: '#/components/schemas/TestCase'
          description: Test cases
        coverage:
          type: number
          format: float
          description: Code coverage percentage (0.0-1.0)
        execution_result:
          type: string
          description: Result of test execution
        confidence:
          type: number
          format: float
          description: Confidence score for test generation (0.0-1.0)

    TestCase:
      type: object
      properties:
        inputs:
          type: object
          description: Input values for the test case
        expected_output:
          type: object
          description: Expected output values
        description:
          type: string
          description: Description of the test case

    AnalysisResult:
      type: object
      properties:
        executed:
          type: boolean
          description: Whether the analysis was executed
        findings:
          type: integer
          description: Number of findings
        execution_time:
          type: number
          format: float
          description: Execution time in seconds

    PerformanceMetrics:
      type: object
      properties:
        loading_time:
          type: number
          format: float
          description: Binary loading time in seconds
        decompilation_time:
          type: number
          format: float
          description: Decompilation time in seconds
        analysis_time:
          type: number
          format: float
          description: Analysis time in seconds
        summarization_time:
          type: number
          format: float
          description: Summarization time in seconds
        test_generation_time:
          type: number
          format: float
          description: Test generation time in seconds
        total_time:
          type: number
          format: float
          description: Total execution time in seconds

    Summary:
      type: object
      properties:
        total_functions:
          type: integer
          description: Total number of functions identified
        total_data_structures:
          type: integer
          description: Total number of data structures identified
        total_tests:
          type: integer
          description: Total number of test harnesses generated
        total_vulnerabilities:
          type: integer
          description: Total number of vulnerabilities detected
        binary_name:
          type: string
          description: Name of the analyzed binary
        analysis_time:
          type: number
          format: float
          description: Total analysis time in seconds

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
