name: Frontend CI

on:
  push:
    branches: [main, master, develop]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [main, master, develop]
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Lint
        working-directory: ./frontend
        run: npm run lint || echo "Linting failed but continuing build"

      - name: Type check
        working-directory: ./frontend
        run: npm run typecheck || echo "Type checking failed but continuing build"

      - name: Build
        working-directory: ./frontend
        run: npm run build

      - name: Test
        working-directory: ./frontend
        run: npm test -- --passWithNoTests

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: frontend/build
